### ISSUE TITLE
Use antq as a library

### ISSUE THREAD

**Issue by tengstrand** [liquidz/antq#209]
Hi!

I'm considering using antq within the [poly](https://polylith.gitbook.io/poly/) tool.

If we let the poly tool execute the [libs](https://polylith.gitbook.io/poly/commands#libs) command, it returns all the used libraries in the workspace, e.g.:
![image](https://user-images.githubusercontent.com/631272/227717520-38d0bf55-3df0-4dd5-b784-d64900587ea2.png)

My idea is to allow the user to also show the column `outdated` that will be populated if the library is out of date, by using antq internally.

I haven't digged into the code so much yet, but is it possible to use antq as a library, and let it return a data structure with all the outdated libraries, when called?

**Comment by pmonks** [comment]
@tengstrand I'm (ab)using `antq` as a library [here](https://github.com/pmonks/pbr/blob/main/src/pbr/tasks.clj#L182-L214). It seems to work ok, despite being a little kludgy due to the entry points and args not being as well-defined as one might expect in a "real" library.

**Comment by liquidz** [comment]
`antq.core/antq` is available, but it has not been organized as an API as you know.
So, I'm considering a new interface based on this function.

**Comment by pmonks** [comment]
@liquidz I _suspect_ it won't take much, given how close the functionality already is! 🤞

**Comment by pmonks** [comment]
@liquidz from my perspective that looks like a good start, though I _think_ some the current [CLI options](https://github.com/liquidz/antq#options) may also be handy to have available via the `opts` map second argument?  For example all of the following seem useful:
* `ignore-locals`
* `check-clojure-tools`
* `transitive` - if/when enhancement #204 is implemented

I think there also needs to be a separate API that's equivalent to the `upgrade` CLI option (imvho it makes more sense to implement this as a separate fn in the API, rather than as an `opt` to `outdated-deps` - obvs that's not possible via a CLI, but an API can be more expressive).

**Comment by liquidz** [comment]
@pmonks Thanks for your advice :)

> I think some of the other [CLI options](https://github.com/liquidz/antq#options) may also be handy to have available via the opts map second argument

Supported.
https://github.com/liquidz/antq/blob/3414e7e0a3ca626dfea1f6b483abfd142d0b4164/src/antq/api.clj#L16

> I think there also needs to be a separate API that's equivalent to the upgrade CLI option

Added.
https://github.com/liquidz/antq/blob/3414e7e0a3ca626dfea1f6b483abfd142d0b4164/src/antq/api.clj#L33

Could you try `dev` branch?

**Comment by tengstrand** [comment]
The new api works really well! Thanks @liquidz

**Comment by liquidz** [comment]
@tengstrand Thanks for your confirmation!
I just released v2.3.1043 :)

**Comment by tengstrand** [comment]
Switched to that version. Thanks @liquidz!
